apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: businessflow
  title: Flujo de negocio
  description: Creaci贸n de un nuevo flujo de negocio
spec:
  owner: guest
  type: service
  parameters:
    - title: Metadata
      properties:
        name:
          title: Flujo de negocio
          type: string
          ui:autofocus: true
        description:
          title: Descripci贸n del flujo
          type: string
          ui:autofocus: true
      required:
        - name
    - title: Infraestructura
      properties:
        provider:
          title: Cloud Provider
          type: string
          enum:
            - aws
            - azure
            - google
          default: aws
        instance-type:
          type: string
          default: m6i.large
        cidr:
          type: string
          default: 172.0.0.0/16
        min-size:
          type: string
          default: "1"
        max-size:
          type: string
          default: "2"
        desired-size:
          type: string
          default: "1"
      required:
        - provider
        - instance-type
        - cidr
        - min-size
        - max-size
        - desired-size

  steps:
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: "Proceso de creaci贸n del flujo de negocio: ${{ parameters.name }}"

    - id: dispatch
      name: Dispatch Businessflow workflow
      action: github:actions:dispatch
      input:
        repoUrl:        'github.com?owner=lima-demos-days&repo=CloudManager'
        workflowId:     businessflow-new.yaml
        branchOrTagName: main
        workflowInputs:
          name:          ${{ parameters.name }}
          description:   ${{ parameters.description }}
          instance_type: ${{ parameters['instance-type'] }}
          cidr:          ${{ parameters.cidr }}
          min_size:      ${{ parameters['min-size'] }}
          max_size:      ${{ parameters['max-size'] }}
          desired_size:  ${{ parameters['desired-size'] }}

  output:
    links:
      - title: Ver ejecuci贸n en GitHub
        url: ${{ steps.dispatch.output.workflowRunUrl }}
        icon: github
